---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: skeleton-01
      PROJECT_ID: azjtp4imscisnfy8crfrxje12x2ln4
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Container Registry (GCR)
      env:
        CREDENCIAL: activate-service-account 192937796538-compute@developer.gserviceaccount.com
      run: |-
        gcloud auth $CREDENCIAL --key-file=key.json
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
    
    - name: Deploy to cluster
      env:
        CREDENCIAL: activate-service-account 192937796538-compute@developer.gserviceaccount.com
      run: |-
        gcloud auth $CREDENCIAL --key-file=key.json
        gcloud components install gke-gcloud-auth-plugin --quiet
        gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project azjtp4imscisnfy8crfrxje12x2ln4
        kubectl set image deployment/app-skeleton mms-cloud-skeleton-1=gcr.io/azjtp4imscisnfy8crfrxje12x2ln4/skeleton-01:${{ github.sha }}
