---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: skeleton-01
      PROJECT_ID: azjtp4imscisnfy8crfrxje12x2ln4
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./scripts/git_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: ${{ github.sha }}
        # GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        CREDENCIAL: activate-service-account 192937796538-compute@developer.gserviceaccount.com
      run: |-
        gcloud auth $CREDENCIAL --key-file=key.json
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    - name: deploy to cluster
      env:
        GIT_TAG: ${{ github.sha }}
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary versionvvv
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/app-skeleton mms-cloud-skeleton-1=$IMAGE_NAME:${{ github.sha }}
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.9 # specify kubectl binary version explicitly
        command: rollout status deployment/hello-v1
